### ISSUE TITLE
error while running from scratch

### ISSUE THREAD

**Issue by tcz001** [wkgg/awesome#2]
I followed the README but fail at ./js/insight/insight-list, anyone know how to fix it?

> 2015-07-02 17:33:03.865 [error][tid:com.facebook.React.JavaScript] "Error: Requiring unknown module "./js/insight/insight-list". If you are sure the module is there, try restarting the packager.
>  stack: 
>   <unknown>       index.ios.bundle:1116
>   require         index.ios.bundle:244
>   applyWithGuard  index.ios.bundle:880
>   require         index.ios.bundle:195
>   <unknown>       index.ios.bundle:56903
>  URL: http://localhost:8081/index.ios.bundle
>  line: 203
>  message: Requiring unknown module "./js/insight/insight-list". If you are sure the module is there, try restarting the packager."
> 2015-07-02 17:33:03.935 [info][tid:com.facebook.React.JavaScript] "Running application "awesome" with appParams: {"rootTag":1,"initialProps":{}}. **DEV** === true, development-level warning are ON, performance optimizations are OFF"
> 2015-07-02 17:33:03.938 [error][tid:com.facebook.React.JavaScript] "Error: Invariant Violation: Application awesome has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
>  stack: 
>   runApplication          index.ios.bundle:36323
>   jsCall                  index.ios.bundle:7372
>   _callFunction           index.ios.bundle:7638
>   <unknown>               index.ios.bundle:7667
>   <unknown>               index.ios.bundle:7661
>   perform                 index.ios.bundle:6194
>   batchedUpdates          index.ios.bundle:13915
>   batchedUpdates          index.ios.bundle:4737
>   <unknown>               index.ios.bundle:7660
>   applyWithErrorReporter  index.ios.bundle:7407
>   guardReturn             index.ios.bundle:7429
>   processBatch            index.ios.bundle:7659
>  URL: http://localhost:8081/index.ios.bundle
>  line: 1758
>  message: Invariant Violation: Application awesome has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent."

**Comment by wkgg** [comment]
@tcz001 that's because insight-List.js file name is not right, I have fix it. besides this if you want to run this app, you also need to set leanCloud App ID and App Key. thanks~
